server:
  port: 8099
spring:
   redis:
      shiro:
        host: 127.0.0.1
        port: 6379
        timeout: 0
        password: 33
   datasource1:
      url: jdbc:mysql://127.0.0.1:3306/guns
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL  
      testWhileIdle: true  
      testOnBorrow: false  
      exceptionSorter: true  
      testOnReturn: false  
      poolPreparedStatements: true  
      filters: stat,wall,log4j  
      maxPoolPreparedStatementPerConnectionSize: 20  
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
